### ISSUE TITLE
보드게임 목록 - 보드게임 리스트

### ISSUE THREAD

**Issue by BNO0** [SuperPlusPoint/boardgame-rental#7]
- [ ] 해당 유저의 DB에 보드게임 목록 request
- [ ] 보드게임 썸네일, 보드게임명, 최소인원, 최대인원
- [ ] 대여가능/대여불가능 여부 표시

**Comment by ParkEunwoo** [comment]
DB 연동을 어케함 그냥 api나 찌르는거지
그리고 store에 데이타 저장 을 굳이 구현 안하려고 react query쓰는건데

**Comment by BNO0** [comment]
수정했슴다
